import React, { useState, useEffect, useRef, useCallback } from 'react';
import { FileText, Loader, AlertTriangle, Download } from 'lucide-react';
import { aiService } from '../services/aiService';
import { useGlucoseFormatting } from '../hooks/useGlucoseFormatting';
import { useDesignMode } from '../contexts/DesignModeContext';
import { format } from 'date-fns';
import {
  Paper,
  Typography,
  Box,
  CircularProgress,
  Alert,
  Button,
  Chip,
  useTheme,
  alpha
} from '@mui/material';
import DownloadIcon from '@mui/icons-material/Download';
import type { NightscoutEntry, NightscoutTreatment } from '../types/nightscout';

interface AIManagementPlanProps {
  readings: NightscoutEntry[];
  treatments: NightscoutTreatment[];
  manualRefresh?: boolean;
}

const AIManagementPlan: React.FC<AIManagementPlanProps> = ({ readings, treatments, manualRefresh = false }) => {
  const { unit, formatGlucoseValue, getUnitLabel, getCurrentGlucoseRanges } = useGlucoseFormatting();
  const { isModern, isPremium } = useDesignMode();
  const theme = useTheme();
  const [plan, setPlan] = useState<string | null>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [generatedDate, setGeneratedDate] = useState<Date | null>(null);
  const [lastAnalyzedData, setLastAnalyzedData] = useState<string>('');
  const initialLoadDone = useRef<boolean>(false);

  const generatePlan = useCallback(async (dataHash: string) => {
    if (!readings || readings.length === 0) return;

    setLoading(true);
    setError(null);

    try {
      const result = await aiService.generateManagementPlan(readings, treatments, { unit, formatGlucoseValue, getUnitLabel, getCurrentGlucoseRanges });

      if (result) {
        setPlan(result);
        setGeneratedDate(new Date());
        setLastAnalyzedData(dataHash);
        initialLoadDone.current = true;
      } else {
        setError('Unable to generate management plan at this time.');
      }
    } catch (err) {
      console.error('Error generating management plan:', err);
      setError('An error occurred while generating your management plan.');
    } finally {
      setLoading(false);
    }
  }, [readings, treatments, unit, formatGlucoseValue, getUnitLabel, getCurrentGlucoseRanges]);

  useEffect(() => {
    // Create a hash of the current data to compare
    const dataHash = `${readings.length}-${treatments.length}`;
    
    // Only generate plan if:
    // 1. We haven't loaded anything yet, OR
    // 2. Manual refresh was requested, OR
    // 3. The data has changed AND we don't have a plan yet
    const shouldGenerate = 
      !initialLoadDone.current || 
      manualRefresh || 
      (dataHash !== lastAnalyzedData && !plan);
    
    if (shouldGenerate && readings?.length > 0 && treatments?.length > 0) {
      generatePlan(dataHash);
    }
  }, [readings, treatments, manualRefresh, lastAnalyzedData, plan, generatePlan]);

  const downloadPlan = () => {
    if (!plan) return;
    
    const title = "Personalized Diabetes Management Plan";
    const date = generatedDate ? `Generated on: ${format(generatedDate, 'MMMM d, yyyy')}` : '';
    
    const content = `
# ${title}
${date}

${plan}

---
This plan was generated by AI based on your diabetes data. Always consult with your healthcare provider before making changes to your diabetes management.
    `;
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `diabetes-management-plan-${format(new Date(), 'yyyy-MM-dd')}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (loading) {
    // Premium Design with Advanced Effects
    if (isPremium) {
      return (
        <Paper 
          elevation={0}
          sx={{ 
            p: 4,
            borderRadius: 3,
            background: `linear-gradient(135deg, ${theme.palette.background.paper} 0%, ${theme.palette.background.default} 100%)`,
            boxShadow: '0 8px 32px rgba(0, 0, 0, 0.08)',
            position: 'relative',
            overflow: 'hidden',
            '&::before': {
              content: '""',
              position: 'absolute',
              top: 0,
              left: 0,
              right: 0,
              height: '4px',
              background: `linear-gradient(90deg, ${theme.palette.primary.main} 0%, ${theme.palette.secondary.main} 100%)`,
            }
          }}
        >
          <Box display="flex" alignItems="center" gap={2} mb={4}>
            <Box
              sx={{
                p: 1.5,
                borderRadius: 2,
                background: `linear-gradient(135deg, ${theme.palette.primary.main} 0%, ${theme.palette.secondary.main} 100%)`,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              <FileText size={24} color="#ffffff" />
            </Box>
            <Typography 
              variant="h5" 
              sx={{ 
                fontWeight: 700,
                background: `linear-gradient(135deg, ${theme.palette.primary.main} 0%, ${theme.palette.secondary.main} 100%)`,
                backgroundClip: 'text',
                WebkitBackgroundClip: 'text',
                color: 'transparent',
              }}
            >
              AI Management Plan
            </Typography>
          </Box>

          <Box 
            display="flex" 
            flexDirection="column" 
            alignItems="center" 
            py={6}
            sx={{
              background: `radial-gradient(circle at center, ${theme.palette.primary.main}08 0%, transparent 70%)`,
              borderRadius: 2,
            }}
          >
            <Box sx={{ position: 'relative', mb: 3 }}>
              <CircularProgress 
                size={64} 
                thickness={3}
                sx={{ 
                  color: theme.palette.primary.main,
                  filter: 'drop-shadow(0 0 8px currentColor)',
                }} 
              />
              <Box
                sx={{
                  position: 'absolute',
                  top: '50%',
                  left: '50%',
                  transform: 'translate(-50%, -50%)',
                  width: 32,
                  height: 32,
                  borderRadius: '50%',
                  background: `linear-gradient(135deg, ${theme.palette.primary.main} 0%, ${theme.palette.secondary.main} 100%)`,
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  fontSize: '16px',
                }}
              >
                🧠
              </Box>
            </Box>
            
            <Typography 
              variant="h6" 
              sx={{ 
                fontWeight: 600,
                mb: 1,
                background: `linear-gradient(135deg, ${theme.palette.text.primary} 0%, ${theme.palette.text.secondary} 100%)`,
                backgroundClip: 'text',
                WebkitBackgroundClip: 'text',
              }}
            >
              Generating your personalized management plan...
            </Typography>
            <Typography variant="body2" color="text.secondary" textAlign="center">
              🔬 Our AI is analyzing your data to create tailored recommendations
            </Typography>
          </Box>
        </Paper>
      );
    }

    // Modern Material UI Design
    if (isModern) {
      return (
        <Paper elevation={2} sx={{ borderRadius: 3, p: 3 }}>
          <Box display="flex" alignItems="center" gap={1} mb={3}>
            <FileText size={24} color={theme.palette.primary.main} />
            <Typography variant="h6" sx={{ fontWeight: 600 }}>
              AI Management Plan
            </Typography>
          </Box>
          <Box display="flex" flexDirection="column" alignItems="center" py={4}>
            <CircularProgress size={48} sx={{ mb: 2, color: theme.palette.primary.main }} />
            <Typography variant="body1" color="text.secondary" textAlign="center">
              Generating your personalized management plan...
            </Typography>
            <Typography variant="body2" color="text.secondary" sx={{ mt: 1 }} textAlign="center">
              This may take a moment as our AI analyzes your data
            </Typography>
          </Box>
        </Paper>
      );
    }

    // Classic Tailwind Design
    return (
      <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-md transition-colors duration-200">
        <div className="flex items-center mb-4">
          <FileText className="h-6 w-6 text-indigo-600 dark:text-indigo-400 mr-2" />
          <h3 className="text-lg font-medium text-gray-900 dark:text-gray-100">AI Management Plan</h3>
        </div>
        <div className="flex flex-col items-center justify-center py-8">
          <Loader className="h-8 w-8 text-indigo-600 dark:text-indigo-400 animate-spin mb-4" />
          <p className="text-gray-600 dark:text-gray-400">Generating your personalized management plan...</p>
          <p className="text-sm text-gray-500 dark:text-gray-500 mt-2">This may take a moment as our AI analyzes your data</p>
        </div>
      </div>
    );
  }

  if (error) {
    // Premium Design with Advanced Effects
    if (isPremium) {
      return (
        <Paper 
          elevation={0}
          sx={{ 
            p: 4,
            borderRadius: 3,
            background: `linear-gradient(135deg, ${theme.palette.background.paper} 0%, ${theme.palette.background.default} 100%)`,
            boxShadow: '0 8px 32px rgba(0, 0, 0, 0.08)',
            position: 'relative',
            overflow: 'hidden',
            '&::before': {
              content: '""',
              position: 'absolute',
              top: 0,
              left: 0,
              right: 0,
              height: '4px',
              background: `linear-gradient(90deg, ${theme.palette.error.main} 0%, ${theme.palette.error.dark} 100%)`,
            }
          }}
        >
          <Box display="flex" alignItems="center" gap={2} mb={3}>
            <Box
              sx={{
                p: 1.5,
                borderRadius: 2,
                background: `linear-gradient(135deg, ${theme.palette.error.main} 0%, ${theme.palette.error.dark} 100%)`,
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'center',
              }}
            >
              <FileText size={24} color="#ffffff" />
            </Box>
            <Typography 
              variant="h5" 
              sx={{ 
                fontWeight: 700,
                background: `linear-gradient(135deg, ${theme.palette.error.main} 0%, ${theme.palette.error.dark} 100%)`,
                backgroundClip: 'text',
                WebkitBackgroundClip: 'text',
                color: 'transparent',
              }}
            >
              AI Management Plan
            </Typography>
          </Box>

          <Alert 
            severity="error" 
            variant="outlined" 
            sx={{ 
              borderRadius: 2,
              background: `linear-gradient(135deg, ${theme.palette.error.main}08 0%, ${theme.palette.error.main}05 100%)`,
              border: `1px solid ${theme.palette.error.main}30`,
            }}
            icon={<AlertTriangle size={20} />}
          >
            <Typography variant="body1" sx={{ fontWeight: 500, mb: 1 }}>
              {error}
            </Typography>
            <Typography variant="body2" color="text.secondary">
              💡 Please try again later or check your API configuration.
            </Typography>
          </Alert>
        </Paper>
      );
    }

    // Modern Material UI Design
    if (isModern) {
      return (
        <Paper elevation={2} sx={{ borderRadius: 3, p: 3 }}>
          <Box display="flex" alignItems="center" gap={1} mb={3}>
            <FileText size={24} color={theme.palette.primary.main} />
            <Typography variant="h6" sx={{ fontWeight: 600 }}>
              AI Management Plan
            </Typography>
          </Box>
          <Alert severity="error" variant="outlined" sx={{ borderRadius: 2 }}>
            <Typography variant="body2" sx={{ fontWeight: 500 }}>
              {error}
            </Typography>
            <Typography variant="caption" sx={{ mt: 0.5, display: 'block' }}>
              Please try again later or check your API configuration.
            </Typography>
          </Alert>
        </Paper>
      );
    }

    // Classic Tailwind Design
    return (
      <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-md transition-colors duration-200">
        <div className="flex items-center mb-4">
          <FileText className="h-6 w-6 text-indigo-600 dark:text-indigo-400 mr-2" />
          <h3 className="text-lg font-medium text-gray-900 dark:text-gray-100">AI Management Plan</h3>
        </div>
        <div className="bg-red-50 dark:bg-red-900/20 p-4 rounded-lg">
          <div className="flex items-start">
            <AlertTriangle className="h-5 w-5 text-red-600 dark:text-red-400 mt-0.5 mr-2 flex-shrink-0" />
            <div>
              <p className="text-red-800 dark:text-red-200">{error}</p>
              <p className="text-sm text-red-700 dark:text-red-300 mt-1">
                Please try again later or check your API configuration.
              </p>
            </div>
          </div>
        </div>
      </div>
    );
  }

  if (!plan) {
    return null;
  }

  // Premium Design with Advanced Effects
  if (isPremium) {
    return (
      <Paper 
        elevation={0}
        sx={{ 
          borderRadius: 3,
          background: `linear-gradient(135deg, ${theme.palette.background.paper} 0%, ${theme.palette.background.default} 100%)`,
          boxShadow: '0 8px 32px rgba(0, 0, 0, 0.08)',
          position: 'relative',
          overflow: 'hidden',
          '&::before': {
            content: '""',
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            height: '4px',
            background: `linear-gradient(90deg, ${theme.palette.primary.main} 0%, ${theme.palette.secondary.main} 100%)`,
          }
        }}
      >
        <Box sx={{ p: 4 }}>
          <Box display="flex" justifyContent="space-between" alignItems="center" mb={4}>
            <Box display="flex" alignItems="center" gap={2}>
              <Box
                sx={{
                  p: 1.5,
                  borderRadius: 2,
                  background: `linear-gradient(135deg, ${theme.palette.primary.main} 0%, ${theme.palette.secondary.main} 100%)`,
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}
              >
                <FileText size={24} color="#ffffff" />
              </Box>
              <Typography 
                variant="h5" 
                sx={{ 
                  fontWeight: 700,
                  background: `linear-gradient(135deg, ${theme.palette.primary.main} 0%, ${theme.palette.secondary.main} 100%)`,
                  backgroundClip: 'text',
                  WebkitBackgroundClip: 'text',
                  color: 'transparent',
                }}
              >
                AI Management Plan
              </Typography>
            </Box>
            {generatedDate && (
              <Chip
                label={`✨ Generated: ${format(generatedDate, 'MMM d, yyyy')}`}
                size="small"
                sx={{
                  background: `linear-gradient(135deg, ${theme.palette.primary.main}20 0%, ${theme.palette.secondary.main}20 100%)`,
                  border: `1px solid ${theme.palette.primary.main}30`,
                  fontWeight: 500,
                }}
              />
            )}
          </Box>

          <Paper 
            elevation={0} 
            sx={{ 
              p: 4,
              background: `linear-gradient(135deg, ${alpha(theme.palette.primary.main, 0.08)} 0%, ${alpha(theme.palette.secondary.main, 0.08)} 100%)`,
              borderRadius: 3,
              mb: 3,
              border: `1px solid ${theme.palette.divider}30`,
              position: 'relative',
              '&::before': {
                content: '""',
                position: 'absolute',
                top: 0,
                left: 0,
                width: '4px',
                height: '100%',
                background: `linear-gradient(180deg, ${theme.palette.primary.main} 0%, ${theme.palette.secondary.main} 100%)`,
                borderRadius: '0 2px 2px 0',
              }
            }}
          >
            <Box sx={{ '& > *:not(:last-child)': { mb: 3 } }}>
              {plan.split('\n').map((paragraph, index) => (
                paragraph.trim() ? (
                  <Typography 
                    key={index} 
                    variant="body1" 
                    sx={{ 
                      lineHeight: 1.7,
                      color: theme.palette.text.primary,
                      fontWeight: paragraph.includes('##') ? 600 : 400,
                      fontSize: paragraph.includes('##') ? '1.1rem' : '1rem',
                    }}
                  >
                    {paragraph.replace(/##/g, '')}
                  </Typography>
                ) : <Box key={index} sx={{ height: 8 }} />
              ))}
            </Box>
          </Paper>

          <Box 
            display="flex" 
            justifyContent="space-between" 
            alignItems="center"
            sx={{
              p: 2.5,
              borderRadius: 2,
              background: `linear-gradient(135deg, ${theme.palette.background.default} 0%, ${theme.palette.background.paper} 100%)`,
              border: `1px solid ${theme.palette.divider}20`,
            }}
          >
            <Typography 
              variant="caption" 
              color="text.secondary"
              sx={{ 
                fontStyle: 'italic',
                display: 'flex',
                alignItems: 'center',
                gap: 1
              }}
            >
              🤖 This plan is generated by AI based on your data. Always consult with your healthcare provider.
            </Typography>
            <Button
              variant="contained"
              size="small"
              startIcon={<DownloadIcon />}
              onClick={downloadPlan}
              sx={{ 
                borderRadius: 2,
                textTransform: 'none',
                fontWeight: 600,
                background: `linear-gradient(135deg, ${theme.palette.primary.main} 0%, ${theme.palette.secondary.main} 100%)`,
                boxShadow: `0 4px 12px ${theme.palette.primary.main}30`,
                '&:hover': {
                  background: `linear-gradient(135deg, ${theme.palette.primary.dark} 0%, ${theme.palette.secondary.dark} 100%)`,
                  boxShadow: `0 6px 16px ${theme.palette.primary.main}40`,
                }
              }}
            >
              Download Plan
            </Button>
          </Box>
        </Box>
      </Paper>
    );
  }

  // Modern Material UI Design
  if (isModern) {
    return (
      <Paper elevation={2} sx={{ borderRadius: 3, overflow: 'hidden' }}>
        <Box sx={{ p: 3 }}>
          <Box display="flex" justifyContent="space-between" alignItems="center" mb={3}>
            <Box display="flex" alignItems="center" gap={1}>
              <FileText size={24} color={theme.palette.primary.main} />
              <Typography variant="h6" sx={{ fontWeight: 600 }}>
                AI Management Plan
              </Typography>
            </Box>
            {generatedDate && (
              <Chip
                label={`Generated: ${format(generatedDate, 'MMM d, yyyy')}`}
                size="small"
                variant="outlined"
                sx={{ fontSize: '0.75rem' }}
              />
            )}
          </Box>

          <Paper 
            elevation={0} 
            sx={{ 
              p: 3,
              backgroundColor: alpha(theme.palette.primary.main, 0.08),
              borderRadius: 2,
              mb: 3
            }}
          >
            <Box sx={{ '& > *:not(:last-child)': { mb: 2 } }}>
              {plan.split('\n').map((paragraph, index) => (
                paragraph.trim() ? (
                  paragraph.startsWith('#') ? (
                    <Typography 
                      key={index} 
                      variant="h6" 
                      sx={{ 
                        fontWeight: 600, 
                        color: theme.palette.primary.main,
                        mt: index > 0 ? 2 : 0 
                      }}
                    >
                      {paragraph.replace(/^#+\s/, '')}
                    </Typography>
                  ) : paragraph.startsWith('*') || paragraph.startsWith('-') ? (
                    <Typography 
                      key={index} 
                      variant="body2" 
                      component="li"
                      sx={{ 
                        listStyleType: 'disc',
                        listStylePosition: 'inside',
                        color: 'text.primary'
                      }}
                    >
                      {paragraph.replace(/^[*-]\s/, '')}
                    </Typography>
                  ) : (
                    <Typography key={index} variant="body2" color="text.primary">
                      {paragraph}
                    </Typography>
                  )
                ) : <br key={index} />
              ))}
            </Box>
          </Paper>

          <Box display="flex" justifyContent="space-between" alignItems="center">
            <Typography variant="caption" color="text.secondary">
              This plan is generated by AI based on your data. Always consult with your healthcare provider.
            </Typography>
            <Button
              variant="contained"
              size="small"
              startIcon={<DownloadIcon />}
              onClick={downloadPlan}
              sx={{ 
                borderRadius: 2,
                textTransform: 'none',
                fontWeight: 500
              }}
            >
              Download Plan
            </Button>
          </Box>
        </Box>
      </Paper>
    );
  }

  // Classic Tailwind Design
  return (
    <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-md transition-colors duration-200">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center">
          <FileText className="h-6 w-6 text-indigo-600 dark:text-indigo-400 mr-2" />
          <h3 className="text-lg font-medium text-gray-900 dark:text-gray-100">AI Management Plan</h3>
        </div>
        {generatedDate && (
          <span className="text-sm text-gray-500 dark:text-gray-400">
            Generated: {format(generatedDate, 'MMM d, yyyy')}
          </span>
        )}
      </div>
      
      <div className="bg-indigo-50 dark:bg-indigo-900/20 p-5 rounded-lg mb-4">
        <div className="prose dark:prose-invert max-w-none text-gray-800 dark:text-gray-200">
          {plan.split('\n').map((paragraph, index) => (
            paragraph.trim() ? (
              paragraph.startsWith('#') ? (
                <h4 key={index} className="font-bold text-indigo-900 dark:text-indigo-100 mt-4 mb-2">
                  {paragraph.replace(/^#+\s/, '')}
                </h4>
              ) : paragraph.startsWith('*') || paragraph.startsWith('-') ? (
                <ul key={index} className="list-disc list-inside my-2">
                  <li>{paragraph.replace(/^[*-]\s/, '')}</li>
                </ul>
              ) : (
                <p key={index} className="my-2">{paragraph}</p>
              )
            ) : <br key={index} />
          ))}
        </div>
      </div>
      
      <div className="flex justify-between items-center">
        <p className="text-xs text-gray-500 dark:text-gray-400">
          This plan is generated by AI based on your data. Always consult with your healthcare provider.
        </p>
        <button
          onClick={downloadPlan}
          className="flex items-center px-3 py-1.5 bg-indigo-600 dark:bg-indigo-500 text-white rounded hover:bg-indigo-700 dark:hover:bg-indigo-600 transition-colors duration-200 text-sm"
        >
          <Download className="h-4 w-4 mr-1" />
          Download Plan
        </button>
      </div>
    </div>
  );
};

export default AIManagementPlan;