import React, { useState, useEffect, useRef } from 'react';
import { FileText, Loader, AlertTriangle, Download } from 'lucide-react';
import { aiService } from '../services/aiService';
import { useGlucoseFormatting } from '../hooks/useGlucoseFormatting';
import { format } from 'date-fns';

interface AIManagementPlanProps {
  readings: any[];
  treatments: any[];
  manualRefresh?: boolean;
}

const AIManagementPlan: React.FC<AIManagementPlanProps> = ({ readings, treatments, manualRefresh = false }) => {
  const { unit, formatGlucoseValue, getUnitLabel, getCurrentGlucoseRanges } = useGlucoseFormatting();
  const [plan, setPlan] = useState<string | null>(null);
  const [loading, setLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);
  const [generatedDate, setGeneratedDate] = useState<Date | null>(null);
  const [lastAnalyzedData, setLastAnalyzedData] = useState<string>('');
  const initialLoadDone = useRef<boolean>(false);

  useEffect(() => {
    // Create a hash of the current data to compare
    const dataHash = `${readings.length}-${treatments.length}`;
    
    // Only generate plan if:
    // 1. We haven't loaded anything yet, OR
    // 2. Manual refresh was requested, OR
    // 3. The data has changed AND we don't have a plan yet
    const shouldGenerate = 
      !initialLoadDone.current || 
      manualRefresh || 
      (dataHash !== lastAnalyzedData && !plan);
    
    if (shouldGenerate && readings?.length > 0 && treatments?.length > 0) {
      generatePlan(dataHash);
    }
  }, [readings, treatments, manualRefresh]);

  const generatePlan = async (dataHash: string) => {
    if (!readings || readings.length === 0) return;
    
    setLoading(true);
    setError(null);
    
    try {
      const result = await aiService.generateManagementPlan(readings, treatments, { unit, formatGlucoseValue, getUnitLabel, getCurrentGlucoseRanges });
      
      if (result) {
        setPlan(result);
        setGeneratedDate(new Date());
        setLastAnalyzedData(dataHash);
        initialLoadDone.current = true;
      } else {
        setError('Unable to generate management plan at this time.');
      }
    } catch (err) {
      console.error('Error generating management plan:', err);
      setError('An error occurred while generating your management plan.');
    } finally {
      setLoading(false);
    }
  };

  const downloadPlan = () => {
    if (!plan) return;
    
    const title = "Personalized Diabetes Management Plan";
    const date = generatedDate ? `Generated on: ${format(generatedDate, 'MMMM d, yyyy')}` : '';
    
    const content = `
# ${title}
${date}

${plan}

---
This plan was generated by AI based on your diabetes data. Always consult with your healthcare provider before making changes to your diabetes management.
    `;
    
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `diabetes-management-plan-${format(new Date(), 'yyyy-MM-dd')}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-md transition-colors duration-200">
        <div className="flex items-center mb-4">
          <FileText className="h-6 w-6 text-indigo-600 dark:text-indigo-400 mr-2" />
          <h3 className="text-lg font-medium text-gray-900 dark:text-gray-100">AI Management Plan</h3>
        </div>
        <div className="flex flex-col items-center justify-center py-8">
          <Loader className="h-8 w-8 text-indigo-600 dark:text-indigo-400 animate-spin mb-4" />
          <p className="text-gray-600 dark:text-gray-400">Generating your personalized management plan...</p>
          <p className="text-sm text-gray-500 dark:text-gray-500 mt-2">This may take a moment as our AI analyzes your data</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-md transition-colors duration-200">
        <div className="flex items-center mb-4">
          <FileText className="h-6 w-6 text-indigo-600 dark:text-indigo-400 mr-2" />
          <h3 className="text-lg font-medium text-gray-900 dark:text-gray-100">AI Management Plan</h3>
        </div>
        <div className="bg-red-50 dark:bg-red-900/20 p-4 rounded-lg">
          <div className="flex items-start">
            <AlertTriangle className="h-5 w-5 text-red-600 dark:text-red-400 mt-0.5 mr-2 flex-shrink-0" />
            <div>
              <p className="text-red-800 dark:text-red-200">{error}</p>
              <p className="text-sm text-red-700 dark:text-red-300 mt-1">
                Please try again later or check your API configuration.
              </p>
            </div>
          </div>
        </div>
      </div>
    );
  }

  if (!plan) {
    return null;
  }

  return (
    <div className="bg-white dark:bg-gray-800 p-6 rounded-lg shadow-md transition-colors duration-200">
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center">
          <FileText className="h-6 w-6 text-indigo-600 dark:text-indigo-400 mr-2" />
          <h3 className="text-lg font-medium text-gray-900 dark:text-gray-100">AI Management Plan</h3>
        </div>
        {generatedDate && (
          <span className="text-sm text-gray-500 dark:text-gray-400">
            Generated: {format(generatedDate, 'MMM d, yyyy')}
          </span>
        )}
      </div>
      
      <div className="bg-indigo-50 dark:bg-indigo-900/20 p-5 rounded-lg mb-4">
        <div className="prose dark:prose-invert max-w-none text-gray-800 dark:text-gray-200">
          {plan.split('\n').map((paragraph, index) => (
            paragraph.trim() ? (
              paragraph.startsWith('#') ? (
                <h4 key={index} className="font-bold text-indigo-900 dark:text-indigo-100 mt-4 mb-2">
                  {paragraph.replace(/^#+\s/, '')}
                </h4>
              ) : paragraph.startsWith('*') || paragraph.startsWith('-') ? (
                <ul key={index} className="list-disc list-inside my-2">
                  <li>{paragraph.replace(/^[*-]\s/, '')}</li>
                </ul>
              ) : (
                <p key={index} className="my-2">{paragraph}</p>
              )
            ) : <br key={index} />
          ))}
        </div>
      </div>
      
      <div className="flex justify-between items-center">
        <p className="text-xs text-gray-500 dark:text-gray-400">
          This plan is generated by AI based on your data. Always consult with your healthcare provider.
        </p>
        <button
          onClick={downloadPlan}
          className="flex items-center px-3 py-1.5 bg-indigo-600 dark:bg-indigo-500 text-white rounded hover:bg-indigo-700 dark:hover:bg-indigo-600 transition-colors duration-200 text-sm"
        >
          <Download className="h-4 w-4 mr-1" />
          Download Plan
        </button>
      </div>
    </div>
  );
};

export default AIManagementPlan;